FROM resin/rpi-raspbian:jessie
MAINTAINER Pascal de Vink <pascal.de.vink@gmail.com>

LABEL Description="Edited from github.com-pascaldevink-rpi-mosquittoclipse"

RUN apt-get update && apt-get install -y iputils-ping
RUN apt-get update && apt-get install -y apt-utils && apt-get install -y wget
RUN apt-get install -y apt-transport-https

RUN wget -q -O - http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key | apt-key add -
RUN wget -q -O /etc/apt/sources.list.d/mosquitto-jessie.list http://repo.mosquitto.org/debian/mosquitto-jessie.list
RUN apt-get update && apt-get install -y mosquitto && apt-get install -y  mosquitto-clients

RUN adduser --system --disabled-password --disabled-login mosquitto


RUN mkdir -p /mqtt/config /mqtt/data /mqtt/log
COPY config /mqtt/config
RUN chown -R mosquitto:mosquitto /mqtt
VOLUME ["/mqtt/config", "/mqtt/data", "/mqtt/log"]

EXPOSE 1883 9001

ADD docker-entrypoint.sh /usr/bin/
ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/usr/sbin/mosquitto","-c","/mqtt/config/mosquitto.conf"]














